import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int t = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int count = t;
		int f2 = 0;
		int f3 = 0;
		int f4 = 0;
		while (count != 0) {
			boolean b = false;
			boolean g = false;
			int sum = 0;
			while (!b || !g){
				sum += 1;
				double c = generator.nextDouble() * 2;
				if (c == 0){
					g = true;
				}
				else {
					b =true;
			
				}
			}
			if (sum == 2){
				f2 += 1;
			}
			else if (sum == 3){
				f3 += 1;
			}
			else {
				f4 +=1;
			}
			count -= 1;
		}
		//double avg = ((2 * f2) + (3 * f3) + (4 * f4)) / (double)t;
		double avg = (2 * f2 + 3 * f3 + 4 * f4) / (double) (f2 + f3 + f4);
		String mode = "4 or more";
		if (f2 >= f3 && f2 >= f4){
			mode = "2"; 
		} 
		else if (f3 >= f4){
			mode = "3";
		}
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + f2);
		System.out.println("Number of families with 3 children: " + f3);
		System.out.println("Number of families with 4 or more children: " + f4);
		System.out.println("The most common number of children is " + mode + ".");

		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
